### ISSUE TITLE
Failed to insert thread /po/xxxxxx into database: error occurred while decoding column 43: unexpected null

### ISSUE THREAD

**Issue by ganrmit** [reasv/mitsuba#11]
Running Mitsuba I just get constant errors of the form:
> mitsuba::archiver::thread_archiver] Failed to insert thread /po/561868 into database: error occurred while decoding column 43: unexpected null; try decoding as an `Option`

Different threads but always column 43. Is this an issue with my config, or perhaps the schema has changed? Threads do still seem to be populating in the database but after several hours no images have yet been downloaded. Not yet sure if this is related to the error.

Any advice you can give would be appreciated as this seems like a great project. Thank you.

**Comment by reasv** [comment]
Mitsuba master is broken at the moment, and I think it's a bug in SQLx. I opened an issue and will consider a workaround if they don't answer
https://github.com/launchbadge/sqlx/issues/3336

Normally you'd get thumbnails in a few seconds; It's not normal for images not to be archived but it's because of this issue.

**Comment by reasv** [comment]
As I mentioned here, I came up with a workaround for the issue: https://github.com/launchbadge/sqlx/issues/3336

See if it works now. I've done very little testing on this change but it seems functional again?

**Comment by ganrmit** [comment]
The previous error is gone, but there's a new one. Threads download, but images do not.

> ERROR  mitsuba::archiver::thread_archiver] Failed to insert image job /pol/474082655 into database: error returned from database: null value in column "file_sha256" of relation "image_backlog" violates not-null constraint

The reasoning they gave you in the sqlx thread of * compiling differently on different machines is gross if true. Good luck with it mate.

**Comment by reasv** [comment]
Should be fixed now. Try again. I hope to get some actual testing on the current master in soon since there's been a lot of changes recently.
Bugs like these are expected given Mitsuba's rust codebase has *doubled* from 2500 to ~5000 LOC since the last release ~3 weeks ago.

A heads up - I plan on squashing migrations before the next release, meaning a database created with the current master branch might not properly upgrade to 1.12 when it comes out. I can help with fixing that if it happens, but I just want to say master might break database compatibility, whereas between versions (eg 1.11 -> 1.12) you'll always be able to upgrade seamlessly. 

I wanted to avoid this but the migrations have become too complex and unmanageable.

**Comment by ganrmit** [comment]
No more database errors. The only problem I have remaining is no images downloading with:

> mitsuba::http] Retry fetching https://i.4cdn.org/pol/1721215391089630.jpg after bad status code (Status: 403 Forbidden)

But I think that's just my connection being blacklisted by the CDN. Thanks mate. I look forward to the future of your project. The full text search is leaps and bounds better than foolfukka.

**Comment by reasv** [comment]
That's cloudflare. Try using proxies

**Comment by ganrmit** [comment]
Marking resolved.
